/*******************************************************************************
	Generated by: DFA of DLL to C version 1.82
	Date: 2019-9-18
	Description: The declaration of functions and variables.
	Website: http://www.dll-decompiler.com
	Technical Support: support@dll-decompiler.com
*******************************************************************************/

#if !defined(D2SL_LEGO1_SUPP_H_00121000_INCLUDED_)
#define D2SL_LEGO1_SUPP_H_00121000_INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#ifdef __cplusplus
extern "C" {
#endif


#include <windows.h>

#include "LEGO1_text.h"
#include "LEGO1_rdata.h"
#include "LEGO1_data.h"
#include "LEGO1_idata.h"


#ifdef __cplusplus
}
#endif


extern HMODULE g_hLEGO1;

extern "C" void __0LegoBackgroundColor__QAE_PBD0_Z();
extern "C" void __0LegoGameState__QAE_XZ();
extern "C" void __0LegoWorld__QAE_XZ();
extern "C" void __0MxAtomId__QAE_PBDW4LookupMode___Z();
extern "C" void __0MxBitmap__QAE_XZ();
extern "C" void __0MxCore__QAE_XZ();
extern "C" void __0MxCriticalSection__QAE_XZ();
extern "C" void __0MxDSAction__QAE_XZ();
extern "C" void __0MxDSFile__QAE_PBDK_Z();
extern "C" void __0MxOmniCreateFlags__QAE_XZ();
extern "C" void __0MxOmniCreateParam__QAE_PBDPAUHWND____AAVMxVideoParam__VMxOmniCreateFlags___Z();
extern "C" void __0MxString__QAE_ABV0__Z();
extern "C" void __0MxVideoParam__QAE_AAV0__Z();
extern "C" void __0MxVideoParam__QAE_AAVMxRect32__PAVMxPalette__KAAVMxVideoParamFlags___Z();
extern "C" void __0MxVideoParam__QAE_XZ();
extern "C" void __0MxVideoParamFlags__QAE_XZ();
extern "C" void __1LegoEntity__UAE_XZ();
extern "C" void __1LegoGameState__QAE_XZ();
extern "C" void __1LegoWorld__UAE_XZ();
extern "C" void __1MXIOINFO__QAE_XZ();
extern "C" void __1MxAtomId__QAE_XZ();
extern "C" void __1MxBitmap__UAE_XZ();
extern "C" void __1MxCore__UAE_XZ();
extern "C" void __1MxCriticalSection__QAE_XZ();
extern "C" void __1MxDSAction__UAE_XZ();
extern "C" void __1MxDSFile__UAE_XZ();
extern "C" void __1MxPresenter__UAE_XZ();
extern "C" void __1MxString__UAE_XZ();
extern "C" void __1MxVideoParam__QAE_XZ();
extern "C" void __4MxAtomId__QAEAAV0_ABV0__Z();
extern "C" void __4MxString__QAEABV0_PBD_Z();
extern "C" void __4MxVideoParam__QAEAAV0_ABV0__Z();
extern "C" void __8MxPalette__QAEEAAV0__Z();
extern "C" void _BackgroundAudioManager__YAPAVMxBackgroundAudioManager__XZ();
extern "C" void _Close_MxDSFile__UAEJXZ();
extern "C" void _Close_MxStreamer__QAEJPBD_Z();
extern "C" void _CreateBackgroundAudio_LegoOmni__QAEXXZ();
extern "C" void _CreateInstance_LegoOmni__SAXXZ();
extern "C" void _CreatePalette_MxBitmap__UAEPAVMxPalette__XZ();
extern "C" void _CreateStreamObject__YAPAVMxDSObject__PAVMxDSFile__F_Z();
extern "C" void _DestroyInstance_MxOmni__SAXXZ();
extern "C" void _Detach_MxPalette__QAEXXZ();
extern "C" void _DisableRMDevice_LegoVideoManager__QAEHXZ();
extern "C" void _DoneTickle_MxPresenter__MAEXXZ();
extern "C" void _Enable_MxBackgroundAudioManager__QAEXE_Z();
extern "C" void _Enable_MxPresenter__UAEXE_Z();
extern "C" void _EnableFullScreenMovie_LegoVideoManager__QAEXEE_Z();
extern "C" void _EnableRMDevice_LegoVideoManager__QAEHXZ();
extern "C" void _EndAction_MxPresenter__UAEXXZ();
extern "C" void _EventManager__YAPAVMxEventManager__XZ();
extern "C" void _FlipToGDISurface_MxDirectDraw__QAEHXZ();
extern "C" void _GameState__YAPAVLegoGameState__XZ();
extern "C" void _GetBufferSize_MxDSFile__UAEKXZ();
extern "C" void _GetCD_MxOmni__SAPBDXZ();
extern "C" void _GetCurrPathInfo_LegoOmni__SAHPAPAVLegoPathBoundary__AAH_Z();
extern "C" void _GetDefaults_LegoNavController__SAXPAHPAM11111111PAE_Z();
extern "C" void _GetHD_MxOmni__SAPBDXZ();
extern "C" void _GetInstance_LegoOmni__SAPAV1_XZ();
extern "C" void _GetInstance_MxOmni__SAPAV1_XZ();
extern "C" void _GetInstance_MxScheduler__SAPAV1_XZ();
extern "C" void _GetNoCD_SourceName__YAPBDXZ();
extern "C" void _GetPartsThreshold_RealtimeView__SAMXZ();
extern "C" void _GetPrimaryBitDepth_MxDirectDraw__SAHXZ();
extern "C" void _GetRealTime_MxTimer__QAEJXZ();
extern "C" void _GetStreamBuffersNum_MxDSFile__UAEKXZ();
extern "C" void _GetUserMaxLOD_RealtimeView__SAMXZ();
extern "C" void _GetVariable_MxVariableTable__QAEPBDPBD_Z();
extern "C" void _Init_MxPresenter__IAEXXZ();
extern "C" void _InputManager__YAPAVLegoInputManager__XZ();
extern "C" void _InvalidateRect_MxVideoManager__QAEXAAVMxRect32___Z();
extern "C" void _IsSound3D_MxOmni__SAEXZ();
extern "C" void _Lego__YAPAVLegoOmni__XZ();
extern "C" void _Load_LegoGameState__QAEJK_Z();
extern "C" void _MSoundManager__YAPAVMxSoundManager__XZ();
extern "C" void _MakeSourceName__YAXPADPBD_Z();
extern "C" void _MoveCursor_LegoVideoManager__QAEXHH_Z();
extern "C" void _MusicManager__YAPAVMxMusicManager__XZ();
extern "C" void _NotificationManager__YAPAVMxNotificationManager__XZ();
extern "C" void _Notify_MxCore__UAEJAAVMxParam___Z();
extern "C" void _Open_MxDSFile__UAEJK_Z();
extern "C" void _Open_MxStreamer__QAEPAVMxStreamController__PBDG_Z();
extern "C" void _ParseExtra_MxPresenter__MAEXXZ();
extern "C" void _Pause_MxDirectDraw__QAEHH_Z();
extern "C" void _PickEntity__YAPAVLegoEntity__JJ_Z();
extern "C" void _PickROI__YAPAVLegoROI__JJ_Z();
extern "C" void _QueueEvent_LegoInputManager__QAEXW4NotificationId__EJJE_Z();
extern "C" void _Read_MxBitmap__UAEJPBD_Z();
extern "C" void _Read_MxDSFile__UAEJPAEK_Z();
extern "C" void _RealizePalette_MxVideoManager__UAEJPAVMxPalette___Z();
extern "C" void _Register_LegoInputManager__QAEXPAVMxCore___Z();
extern "C" void _RemoveAll_ViewManager__QAEXPAVViewROI___Z();
extern "C" void _RemoveWorld_LegoOmni__QAEXABVMxAtomId__J_Z();
extern "C" void _Save_LegoGameState__QAEJK_Z();
extern "C" void _Seek_MxDSFile__UAEJJH_Z();
extern "C" void _SerializePlayersInfo_LegoGameState__QAEXF_Z();
extern "C" void _SerializeScoreHistory_LegoGameState__QAEXF_Z();
extern "C" void _SetCD_MxOmni__SAXPBD_Z();
extern "C" void _SetDefaults_LegoNavController__SAXHMMMMMMMMME_Z();
extern "C" void _SetDeviceName_MxVideoParam__QAEXPAD_Z();
extern "C" void _SetDisplayBB_LegoROI__QAEXH_Z();
extern "C" void _SetDoMutex_MxCriticalSection__SAXXZ();
extern "C" void _SetHD_MxOmni__SAXPBD_Z();
extern "C" void _SetObjectName_MxDSObject__QAEXPBD_Z();
extern "C" void _SetOmniUserMessage__YAXP6AXPBDH_Z_Z();
extern "C" void _SetPartsThreshold_RealtimeView__SAXM_Z();
extern "C" void _SetSavePath_LegoGameState__QAEXPAD_Z();
extern "C" void _SetSound3D_MxOmni__SAXE_Z();
extern "C" void _SetUserMaxLOD_RealtimeView__SAXM_Z();
extern "C" void _SetVariable_MxVariableTable__QAEXPAVMxVariable___Z();
extern "C" void _SetVariable_MxVariableTable__QAEXPBD0_Z();
extern "C" void _SetWaitIndicator_MxTransitionManager__QAEXPAVMxVideoPresenter___Z();
extern "C" void _SoundManager__YAPAVLegoSoundManager__XZ();
extern "C" void _Start__YAJPAVMxDSAction___Z();
extern "C" void _StartAction_MxPresenter__UAEJPAVMxStreamController__PAVMxDSAction___Z();
extern "C" void _StartMultiTasking_MxScheduler__QAEXK_Z();
extern "C" void _Streamer__YAPAVMxStreamer__XZ();
extern "C" void _Tickle_MxPresenter__UAEJXZ();
extern "C" void _TickleManager__YAPAVMxTickleManager__XZ();
extern "C" void _Timer__YAPAVMxTimer__XZ();
extern "C" void _TransitionManager__YAPAVMxTransitionManager__XZ();
extern "C" void _UnRegister_LegoInputManager__QAEXPAVMxCore___Z();
extern "C" void _VariableTable__YAPAVMxVariableTable__XZ();
extern "C" void _VideoManager__YAPAVLegoVideoManager__XZ();
extern "C" void _configureLegoAnimationManager_LegoAnimationManager__SAXH_Z();
extern "C" void _configureLegoBuildingManager_LegoBuildingManager__SAXH_Z();
extern "C" void _configureLegoModelPresenter_LegoModelPresenter__SAXH_Z();
extern "C" void _configureLegoPartPresenter_LegoPartPresenter__SAXHH_Z();
extern "C" void _configureLegoROI_LegoROI__SAXH_Z();
extern "C" void _configureLegoWorldPresenter_LegoWorldPresenter__SAXH_Z();
extern "C" void _DllMain_12();

/* All the not exported functions redirect to this function. */
void _LEGO1_NotExported();

#endif // !defined(D2SL_LEGO1_SUPP_H_00121000_INCLUDED_)